### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by mlajkim** [ajktown/api#49]
## Background

Users should have the ability to manually adjust the language setting. Alternatively, the API should automatically detect and save the language of the posted word, without UI given.

## TODOs
- [x] Automatic Language Detection implemented
- [x] k8s related deployments modified
- [x] env file modified
- [x] env sample file modified

**Comment by mlajkim** [comment]
Handled on https://github.com/ajktown/api/pull/54
