### ISSUE TITLE
Search Bug Fix

### ISSUE THREAD

**Issue by mlajkim** [ajktown/api#55]
# Background
I clearly have a word "乗算" but the Wordnote fails to search, probably due to the request data as the following
`Params: {"semester":233,"searchInput":"乗算","pageIndex":0}`

![image](https://github.com/ajktown/api/assets/53258958/1421e423-d25e-459d-99e7-9cbb4ec5a0b4)

## TODOs
```
- [ ] If searchInput is not empty, it should ignore the given pageIndex ...? (What if there are multiple searches match then...?)
- [ ] The semester or other tags must be ignored
- [ ] Write more TODOs
```

**Comment by mlajkim** [comment]
This is not a bug and API is actually doing as requested. The FE should be smart enough to ask for searchInput only, when user wants to search. (It is the FE's design decision, not API's decision) 
This issue is rejected and closed as it is not considered bug as claimed.

fyi:
The wgt had the problem and was fixed in https://github.com/ajktown/wordnote/pull/179.
